version = 1

[[analyzers]]
name = "docker"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["vue"]

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "prettier"
enabled = true